### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-1-evaluacion-intermedia-sarapalcam#1]
Muy buen trabajo @sarapalcam!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta `h1`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > COLOR: El color del h1 debe ser blanco (revísalo cuando lo añadas).
- [x] CSS > COLOR: El color de los enlaces debe ser  4a4a4a
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik (igualmente, revísalo cuando lo añadas).
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px (como es ahora en la `<section>`. Aplica al `<h1>` la clase main-text).
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px (como es ahora en la `<section>`. Aplica al `<h1>` la clase main-text).
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño(pon el padding en los `<a>`, repartiéndolos entre ambos, en lugar de en los `<li>`).
- [x] CSS > FLEX: La mejor forma de centrar el texto principal es con flex (la verdad es que el top,left 50% que has usado también está bien).

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, **márcala como completada en este issue** y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by sarapalcam** [comment]
Hola Iván! Ya subí una nueva versión del ejercicio corregida. Varios de los cambios que me sugería el bot eran cosas que ya estaban hechas. Entiendo que es algo normal, pero no sé si os viene bien saber cuáles eran, así que he dejado sin marcar todos los comentarios que ya estaban bien en la versión original.
Gracias!

**Comment by igarridomorillas** [comment]
Perfecto, todo hecho!
